name: Firmware Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PICO_SDK_URL: https://github.com/raspberrypi/pico-sdk.git
      PICO_SDK_VERSION: 1.3.1
      ARM_URL_COMMON: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10
      ARM_FILENAME_LINUX: gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
      ARM_DIR: arm-toolchain

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Raspberry Pi Pico SDK and submodules
        run: |
          mkdir deps
          cd deps
          git clone ${PICO_SDK_URL} -b ${PICO_SDK_VERSION} --depth 1
          cd pico-sdk
          git submodule init
          git submodule update --depth 1

      - name: Download and install the ARM toolchain
        run: |
          cd deps
          wget --progress=dot:giga ${ARM_URL_COMMON}/${ARM_FILENAME_LINUX}
          mkdir ${ARM_DIR}
          tar jxf ${ARM_FILENAME_LINUX} --directory ${ARM_DIR} --strip-components 1
          rm ${ARM_FILENAME_LINUX}

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: |
          cmake --build build
          ls -l build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: alpakka
          path: build/alpakka.uf2
